Projects/DeployTools.Web/Pages/ActiveDeployments.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DeployTools.Core.DataAccess.Entities;
using DeployTools.Core.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class ActiveDeploymentsModel(IHostsService hostsService, 
        IPackagesService packagesService,
        IApplicationsService applicationsService,
        IDeploymentsService deploymentsService) : PageModel
    {
        [BindProperty] public IList<ActiveDeploymentExtended> ActiveDeployments { get; set; }
        [BindProperty] public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGet()
        {
            var activeDeployments = await deploymentsService.GetAllActiveDeploymentsAsync();

            ActiveDeployments = new List<ActiveDeploymentExtended>();

            var hosts = await hostsService.GetAllAsync();
            var packages = await packagesService.GetAllAsync();
            var applications = await applicationsService.GetAllAsync();

            foreach (var deployment in activeDeployments)
            {
                var o = new ActiveDeploymentExtended
                {
                    Id = deployment.Id,
                    CreatedAt = deployment.CreatedAt,
                    PackageId = deployment.PackageId,
                    HostId = deployment.HostId,
                    Port = deployment.Port,
                    ApplicationId = deployment.ApplicationId,
                    DeployId = deployment.DeployId,
                    HostAddress = hosts.First(x => x.Id == deployment.HostId).Address,
                    PackageName = packages.First(x => x.Id == deployment.PackageId).Name,
                    ApplicationName = applications.First(x => x.Id == deployment.ApplicationId).Name
                };

                ActiveDeployments.Add(o);
            }

            return Page();
        }

        public async Task<IActionResult> OnPostTakeDown()
        {
            var id = Request.Form["id"];

            var deployment = await deploymentsService.GetActiveDeploymentByIdAsync(id);
            if (deployment is null)
            {
                return NotFound();
            }

            await deploymentsService.StartTakeDownAsync(id);

            return await OnGet();
        }
    }

    public class ActiveDeploymentExtended : ActiveDeployment
    {
        public string ApplicationName { get; set; }
        public string HostAddress { get; set; }
        public string PackageName { get; set; }
    }
}

Projects/DeployTools.Web/Pages/ApplicationCreate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using DeployTools.Core.DataAccess.Entities;
using DeployTools.Core.Services.Interfaces;
using DeployTools.Web.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class ApplicationCreateModel(IApplicationsService applicationsService, IPackagesService packagesService, IRdsPackagesService rdsPackagesService) : PageModel
    {
        [BindProperty] public Application Application { get; set; }
        [BindProperty] public string ErrorMessage { get; set; }
        public IList<Package> ValidPackages { get; set; }
        public IList<RdsPackage> ValidRdsPackages { get; set; }

        public async Task<IActionResult> OnGet()
        {
            Application = new Application();

            ValidPackages = await packagesService.GetAllAsync();
            ValidRdsPackages = await rdsPackagesService.GetAllAsync();

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            var error = await Application.ValidateApplication(applicationsService);
            if (error is not null)
            {
                ErrorMessage = error;
                return Page();
            }

            if (Application.RdsPackageId.Equals("NONE", StringComparison.CurrentCultureIgnoreCase))
            {
                Application.RdsPackageId = null;
            }

            await applicationsService.SaveAsync(Application);
            
            return RedirectToPage("/Applications");
        }
    }
}

Projects/DeployTools.Web/Pages/ApplicationDeploy.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using DeployTools.Core.DataAccess.Entities;
using DeployTools.Core.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class ApplicationDeployModel(IHostsService hostsService, 
        IApplicationsService applicationsService,
        IDeploymentsService deploymentsService,
        ICertificatesService certificatesService): PageModel
    {
        [BindProperty] public ApplicationDeployExtended ApplicationDeploy { get; set; }
        [BindProperty] public string ErrorMessage { get; set; }
        public IList<Host> Hosts { get; set; }

        public async Task<IActionResult> OnGet(string id)
        {
            var application = await applicationsService.GetByIdAsync(id);
            if (application is null)
            {
                return NotFound();
            }
            
            Hosts = await hostsService.GetAllAsync();

            ApplicationDeploy = new ApplicationDeployExtended
            {
                ApplicationName = application.Name
            };

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            var id = Request.Query["id"];

            var application = await applicationsService.GetByIdAsync(id);
            if (application is null)
            {
                return NotFound();
            }

            var certificate = await certificatesService.GetCertificateByDomainAsync(application.Domain);
            if (certificate is null)
            {
                ErrorMessage = "No certificate found for application domain";
                return await OnGet(id);
            }

            if (certificate.IsMarkedForDeletion)
            {
                ErrorMessage = "The certificate for this application is marked for deletion";
                return await OnGet(id);
            }

            if (!certificate.IsValidated)
            {
                ErrorMessage = "The certificate for this application has not been yet validated";
                return await OnGet(id);
            }

            if (!certificate.IsCreated)
            {
                ErrorMessage = "The certificate for this application has not yet been created";
                return await OnGet(id);
            }

            await deploymentsService.StartDeploymentAsync(id, ApplicationDeploy.HostId);

            return RedirectToPage("/Applications");
        }
    }

    public class ApplicationDeployExtended
    {
        public string ApplicationName { get; set; }
        public string HostId { get; set; }
    }
}

Projects/DeployTools.Web/Pages/ApplicationEdit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using DeployTools.Core.DataAccess.Entities;
using DeployTools.Core.Services.Interfaces;
using DeployTools.Web.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class ApplicationEditModel(IApplicationsService applicationsService, IPackagesService packagesService, IRdsPackagesService rdsPackagesService) : PageModel
    {
        [BindProperty] public Application Application { get; set; }
        [BindProperty] public string ErrorMessage { get; set; }
        public IList<Package> ValidPackages { get; set; }
        public IList<RdsPackage> ValidRdsPackages { get; set; }

        public async Task<IActionResult> OnGet(string id)
        {
            Application = await applicationsService.GetByIdAsync(id);
            if (Application is null)
            {
                return NotFound();
            }

            ValidPackages = await packagesService.GetAllAsync();
            ValidRdsPackages = await rdsPackagesService.GetAllAsync();

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            var existingApplication = await applicationsService.GetByIdAsync(Request.Query["id"]);
            if (existingApplication is null)
            {
                return NotFound();
            }

            Application.Id = existingApplication.Id;
            Application.Name = existingApplication.Name;

            var error = await Application.ValidateApplication(applicationsService);
            if (error is not null)
            {
                ErrorMessage = error;
                return await OnGet(Request.Query["id"]);
            }

            existingApplication.Domain = Application.Domain;
            existingApplication.PackageId = Application.PackageId;
            existingApplication.RdsPackageId = Application.RdsPackageId.Equals("NONE", StringComparison.InvariantCultureIgnoreCase)
                    ? null
                    : Application.RdsPackageId;

            await applicationsService.UpdateAsync(existingApplication);
            
            return RedirectToPage("/Applications");
        }
    }
}

Projects/DeployTools.Web/Pages/Applications.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DeployTools.Core.DataAccess.Entities;
using DeployTools.Core.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class ApplicationExtended : Application
    {
        public string PackageName { get; set; }
        public string RdsPackageName { get; set; }
    }

    public class ApplicationsModel(IApplicationsService applicationsService, 
        IPackagesService packagesService,
        IRdsPackagesService rdsPackagesService,
        IDeploymentsService deploymentsService) : PageModel
    {
        [BindProperty] public IList<ApplicationExtended> Applications { get; set; }
        [BindProperty] public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGet()
        {
            var applications = await applicationsService.GetAllAsync();
            var packages = await packagesService.GetAllAsync();
            var rdsPackages = await rdsPackagesService.GetAllAsync();

            Applications = new List<ApplicationExtended>();
            foreach (var application in applications)
            {
                var package = packages.First(x => x.Id == application.PackageId);
                var rdsPackageName = string.IsNullOrEmpty(application.RdsPackageId)
                    ? string.Empty
                    : rdsPackages.First(x => x.Id == application.RdsPackageId).Name;
                Applications.Add(new()
                {
                    Id = application.Id,
                    Name = application.Name,
                    Domain = application.Domain,
                    PackageId = application.PackageId,
                    CreatedAt = application.CreatedAt,
                    PackageName = package.Name,
                    RdsPackageName = rdsPackageName
                });
            }

            return Page();
        }

        public async Task<IActionResult> OnPostDelete()
        {
            var id = Request.Form["id"];

            var application = await applicationsService.GetByIdAsync(id);
            if (application is null)
            {
                return NotFound();
            }

            var deployments = await deploymentsService.GetActiveDeploymentsOfApplicationAsync(application.Id);
            if (deployments.Count > 0)
            {
                ErrorMessage = $"Application is deployed in {deployments.Count} active deployments and cannot be deleted";
                return await OnGet();
            }

            await applicationsService.DeleteAsync(application);

            return await OnGet();
        }
    }
}

Projects/DeployTools.Web/Pages/CertificateCreate.cshtml.cs
using System.Threading.Tasks;
using DeployTools.Core.DataAccess.Entities;
using DeployTools.Core.Services.Interfaces;
using DeployTools.Web.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class CertificateCreateModel(ICertificatesService certificatesService) : PageModel
    {
        [BindProperty]
        public Certificate Certificate { get; set; }

        [BindProperty]
        public string ErrorMessage { get; set; }

        public IActionResult OnGet()
        {
            Certificate = new Certificate();

            return Page();
        }

        public async Task<IActionResult> OnPost()
        {
            var error = await Certificate.ValidateCertificate(certificatesService);
            if (error is not null)
            {
                ErrorMessage = error;
                return Page();
            }

            Certificate.IsCreated = false;
            Certificate.IsValidated = false;

            await certificatesService.SaveAsync(Certificate);
            
            return RedirectToPage("/Certificates");
        }
    }
}

Projects/DeployTools.Web/Pages/Certificates.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using DeployTools.Core.DataAccess.Entities;
using DeployTools.Core.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class CertificatesModel(ICertificatesService certificatesService, 
        IApplicationsService applicationsService,
        IDeploymentsService deploymentsService) : PageModel
    {
        [BindProperty] public IList<Certificate> Certificates { get; set; }
        [BindProperty] public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGet()
        {
            Certificates = await certificatesService.GetAllAsync();

            return Page();
        }

        public async Task<IActionResult> OnPostDelete()
        {
            var id = Request.Form["id"];

            var certificate = await certificatesService.GetByIdAsync(id);
            if (certificate is null)
            {
                return NotFound();
            }

            var applications = await applicationsService.GetApplicationsByDomainAsync(certificate.Domain);
            if (applications.Count is > 0)
            {
                foreach (var application in applications)
                {
                    var deployed = await deploymentsService.GetActiveDeploymentsOfApplicationAsync(application.Id);
                    if (deployed.Count is > 0)
                    {
                        ErrorMessage =
                            $"Cannot delete certificate, in use by deployed application {application.Name} in {deployed.Count} deployments";
                        return await OnGet();
                    }
                }
            }

            certificate.IsMarkedForDeletion = true;

            await certificatesService.UpdateAsync(certificate);

            return await OnGet();
        }
    }
}

Projects/DeployTools.Web/Pages/DeployJournal.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using DeployTools.Core.DataAccess.Entities;
using DeployTools.Core.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class DeployJournalModel(IDeploymentsService deploymentsService) : PageModel
    {
        [BindProperty] public IList<JournalEntry> JournalEntries { get; set; }

        public async Task<IActionResult> OnGet(string id)
        {
            JournalEntries = await deploymentsService.GetJournalEntriesOfDeployAsync(id);

            return Page();
        }
    }
}

Projects/DeployTools.Web/Pages/Deployments.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using DeployTools.Core.DataAccess.Entities;
using DeployTools.Core.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class DeploymentsModel(IDeploymentsService deploymentsService) : PageModel
    {
        [BindProperty] public IList<ApplicationDeploy> Deployments { get; set; }

        public async Task<IActionResult> OnGet()
        {
            Deployments = await deploymentsService.GetAllDeploymentsAsync();

            return Page();
        }
    }
}

Projects/DeployTools.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;
using Microsoft.Extensions.Logging;

namespace DeployTools.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Projects/DeployTools.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class IndexModel : PageModel;
}

Projects/DeployTools.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace DeployTools.Web.Pages
{
    public class PrivacyModel : PageModel;

}

Projects/DeployTools.Web/Pages/ActiveDeployments.cshtml
@page
@model DeployTools.Web.Pages.ActiveDeploymentsModel
@{
    ViewData["Title"] = "Active deployments";
}
@{
    <main class="pri_color_3_background pt-2">
    <div class="container mt-4">
        <h1 class="mb-4">Active Deployments List</h1>

        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div class="alert alert-danger" role="alert">
                @Model.ErrorMessage
            </div>
        }

        @if (Model.ActiveDeployments is { Count: > 0 })
        {
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Host ID</th>
                    <th>Address</th>
                    <th>Port</th>
                    <th>Package</th>
                    <th>Application</th>
                    <th>RDS ARN</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var deployment in Model.ActiveDeployments)
                {
                    <tr>
                        <td>@deployment.Id</td>
                        <td>@deployment.HostId</td>
                        <td>@deployment.HostAddress</td>
                        <td>@deployment.Port</td>
                        <td>@deployment.PackageName</td>
                        <td>@deployment.ApplicationName</td>
                        <td>@deployment.RdsArn</td>
                        <td>@deployment.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")</td>
                        <td>
                            <form method="post" onsubmit="confirmDelete(event)">
                                <input type="hidden" name="id" value="@deployment.Id"/>
                                <button type="submit" asp-page-handler="TakeDown" class="btn btn-danger btn-sm">Take down</button>
                            </form>
                            <form method="get" action="/DeployJournal" class="d-inline">
                                <input type="hidden" name="id" value="@deployment.DeployId" />
                                <button type="submit" class="btn btn-dark btn-sm mt-1">View journal</button>
                            </form>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        }
        else
        {
            <p>No active deployments found.</p>
        }
    </div>
</main>
}
@section Scripts
{
    <script>
        function confirmDelete(event) {
            if (!confirm("Are you sure you want to take down this deployment? This action cannot be undone.")) {
                event.preventDefault();
            }
        }
    </script>
}

Projects/DeployTools.Web/Pages/Applications.cshtml
@page
@model DeployTools.Web.Pages.ApplicationsModel
@{
    ViewData["Title"] = "Applications";
}
@{
    <main class="pri_color_3_background pt-2">
    <div class="container mt-4">
        <h1 class="mb-4">Applications List</h1>
        <div class="mb-3">
            <form method="get" action="/ApplicationCreate">
                <button type="submit" class="btn btn-success">New Application</button>
            </form>
        </div>
        
        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div class="alert alert-danger" role="alert">
                @Model.ErrorMessage
            </div>
        }

        @if (Model.Applications is { Count: > 0 })
        {
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Package</th>
                    <th>Domain</th>
                    <th>RDS Package</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var application in Model.Applications)
                {
                    <tr>
                        <td>@application.Id</td>
                        <td>@application.Name</td>
                        <td>@application.PackageName</td>
                        <td>@application.Domain</td>
                        <td>@application.RdsPackageName</td>
                        <td>@application.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")</td>
                        <td>
                            <form method="post">
                                <input type="hidden" name="id" value="@application.Id" />
                                <button type="submit" asp-page-handler="Delete"  class="btn btn-danger btn-sm">Delete</button>
                            </form>
                            <form method="get" action="/ApplicationEdit" class="d-inline">
                                <input type="hidden" name="id" value="@application.Id" />
                                <button type="submit" class="btn btn-primary btn-sm mt-1">Edit</button>
                            </form>
                            <form method="get" action="/ApplicationDeploy" class="d-inline">
                                <input type="hidden" name="id" value="@application.Id" />
                                <button type="submit" class="btn btn-dark btn-sm mt-1">Deploy</button>
                            </form>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        }
        else
        {
            <p>No applications found.</p>
        }
    </div>
    </main>
}

Projects/DeployTools.Web/Pages/Certificates.cshtml
@page
@using NHibernate.Id
@model DeployTools.Web.Pages.CertificatesModel
@{
    ViewData["Title"] = "Certificates";
}
@{
    <main class="pri_color_3_background pt-2">
    <div class="container mt-4">
        <h1 class="mb-4">Certificates List</h1>
        <div class="mb-3">
            <form method="get" action="/CertificateCreate">
                <button type="submit" class="btn btn-success">New Certificate</button>
            </form>
        </div>
        
        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div class="alert alert-danger" role="alert">
                @Model.ErrorMessage
            </div>
        }

        @if (Model.Certificates is { Count: > 0 })
        {
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Domain</th>
                    <th>ARN</th>
                    <th>Certificate ID</th>
                    <th>Created</th>
                    <th>Validated</th>
                    <th>Marked for deletion</th>
                    <th>Validation Info</th>
                    <th>Expires At</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var certificate in Model.Certificates)
                {
                    <tr>
                        <td>@certificate.Id</td>
                        <td>@certificate.Domain</td>
                        <td>@certificate.Arn</td>
                        <td>@certificate.CertificateId</td>
                        <td>@certificate.IsCreated</td>
                        <td>@certificate.IsValidated</td>
                        <td>@certificate.IsMarkedForDeletion</td>
                        <td>@certificate.ValidationInfo</td>
                        <td>@certificate.ExpiresAt?.ToString("yyyy-MM-dd HH:mm:ss")</td>
                        <td>@certificate.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")</td>
                        <td>
                            @if (!certificate.IsMarkedForDeletion)
                            {
                                <form method="post">
                                    <input type="hidden" name="id" value="@certificate.Id"/>
                                    <button type="submit" asp-page-handler="Delete" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            }
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        }
        else
        {
            <p>No certificates found.</p>
        }
    </div>
    </main>
}

Projects/DeployTools.Web/Pages/Hosts.cshtml
@page
@model DeployTools.Web.Pages.HostsModel
@{
    ViewData["Title"] = "Hosts";
}
@{
    <main class="pri_color_3_background pt-2">
    <div class="container mt-4">
        <h1 class="mb-4">Host List</h1>
        <div class="mb-3">
            <form method="get" action="/HostCreate">
                <button type="submit" class="btn btn-success">New Host</button>
            </form>
        </div>
        
        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div class="alert alert-danger" role="alert">
                @Model.ErrorMessage
            </div>
        }

        @if (Model.Hosts is { Count: > 0 })
        {
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Address</th>
                    <th>Instance ID</th>
                    <th>SSH Username</th>
                    <th>Key File</th>
                    <th>Next Free Port</th>
                    <th>Load Balancer ARN</th>
                    <th>VPC ID</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var host in Model.Hosts)
                {
                    <tr>
                        <td>@host.Id</td>
                        <td>@host.Address</td>
                        <td>@host.InstanceId</td>
                        <td>@host.SshUserName</td>
                        <td>@host.KeyFile</td>
                        <td>@host.NextFreePort</td>
                        <td>@host.AssignedLoadBalancerArn</td>
                        <td>@host.VpcId</td>
                        <td>@host.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")</td>
                        <td>
                            <form method="post">
                                <input type="hidden" name="id" value="@host.Id" />
                                <button type="submit" asp-page-handler="Delete"  class="btn btn-danger btn-sm">Delete</button>
                            </form>
                            <form method="get" action="/HostEdit" class="d-inline">
                                <input type="hidden" name="id" value="@host.Id" />
                                <button type="submit" class="btn btn-primary btn-sm mt-1">Edit</button>
                            </form>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        }
        else
        {
            <p>No hosts found.</p>
        }
    </div>
    </main>
}

Projects/DeployTools.Web/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

Projects/DeployTools.Web/Pages/Packages.cshtml
@page
@model DeployTools.Web.Pages.PackagesModel
@{
    ViewData["Title"] = "Packages";
}
@{
    <main class="pri_color_3_background pt-2">
    <div class="container mt-4">
        <h1 class="mb-4">Packages List</h1>
        <div class="mb-3">
            <form method="get" action="/PackageCreate">
                <button type="submit" class="btn btn-success">New Package</button>
            </form>
        </div>
        
        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div class="alert alert-danger" role="alert">
                @Model.ErrorMessage
            </div>
        }

        @if (Model.Packages is { Count: > 0 })
        {
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Deployable location</th>
                    <th>Executable file</th>
                    <th>Created At</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var package in Model.Packages)
                {
                    <tr>
                        <td>@package.Id</td>
                        <td>@package.Name</td>
                        <td>@package.DeployableLocation</td>
                        <td>@package.ExecutableFile</td>
                        <td>@package.CreatedAt.ToString("yyyy-MM-dd HH:mm:ss")</td>
                        <td>
                            <form method="post">
                                <input type="hidden" name="id" value="@package.Id" />
                                <button type="submit" asp-page-handler="Delete"  class="btn btn-danger btn-sm">Delete</button>
                            </form>
                            <form method="get" action="/PackageEdit" class="d-inline">
                                <input type="hidden" name="id" value="@package.Id" />
                                <button type="submit" class="btn btn-primary btn-sm mt-1">Edit</button>
                            </form>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        }
        else
        {
            <p>No hosts found.</p>
        }
    </div>
    </main>
}